### ISSUE TITLE
usable as a crate / lib?

### ISSUE THREAD

**Issue by ReeceM** [grimace87/Stitchy#3]
Hello,

Just want to know if this is usable as a crate in another rust program?

I'm not sure if it is possible or if this is only meant to be a CLI program. Given that this doesn't rely on all the fancy CV libs like opencv or similar it seems to be light enough.

Any feedback is appreciated :)

> Reece

**Comment by shining-grimace** [comment]
Hi Reece,
In its current state, the project is only usable as a CLI binary, though it should be easy enough to extract out a library API and publish that as a separate crate. I'll add this to my to-do list.
There are a few updates I want to make to this project already, and I'll get onto everything in the next couple of weeks or so.

**Comment by ReeceM** [comment]
Hi @grimace87 

thanks for the feedback and I look forward to using it as a library. I don't need to use it immediately so can wait for you to update it when you do.

Thanks again for coming back with info 👍

**Comment by shining-grimace** [comment]
Hey @ReeceM,

Apologies for the delay. The changes I intended to make are all done, including publishing the separate crate [stitchy-core](https://crates.io/crates/stitchy-core). I've tried to keep the API lean but effective and well-documented.
Any feedback on issues you have with it, or on anything at all, is much appreciated!

Cheers,
Thomas

**Comment by ReeceM** [comment]
Hey @grimace87,

That's awesome, thank you. And you didn't delay at all 👍

I'll definitely be checking it out and give feedback on it if there are any bugs. But will let you know how that it works for me 👍

Kind Regards
Reece
